BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Pessoa" (
	"ID_PESSOA"	INTEGER NOT NULL,
	"NOME"	TEXT NOT NULL,
	"TELEFONE"	TEXT NOT NULL,
	"EMAIL"	TEXT NOT NULL,
	"ENDERECO"	TEXT NOT NULL,
	"CARGO"	TEXT,
	PRIMARY KEY("ID_PESSOA")
);
CREATE TABLE IF NOT EXISTS "Experiencias" (
	"ID_EXPERIENCIAS"	INTEGER NOT NULL,
	"NOME DA EMPRESA"	TEXT NOT NULL,
	"CARGO"	TEXT NOT NULL,
	"DURACAO"	TEXT NOT NULL,
	"DESCRICAO"	TEXT NOT NULL,
	"ID_PESSOA"	INTEGER,
	PRIMARY KEY("ID_EXPERIENCIAS"),
	FOREIGN KEY("ID_PESSOA") REFERENCES "Pessoa"("ID_PESSOA")
);
CREATE TABLE IF NOT EXISTS "Formacao" (
	"ID_FORMACAO"	INTEGER NOT NULL,
	"CURSO"	TEXT NOT NULL,
	"DURACAO"	TEXT NOT NULL,
	"DESCRICAO"	TEXT NOT NULL,
	"ID_PESSOA"	INTEGER,
	PRIMARY KEY("ID_FORMACAO"),
	FOREIGN KEY("ID_PESSOA") REFERENCES "Pessoa"("ID_PESSOA")
);
CREATE TABLE IF NOT EXISTS "Realizacoes" (
	"ID_REALIZACOES"	INTEGER NOT NULL,
	"NOME"	TEXT NOT NULL,
	"DATA"	TEXT NOT NULL,
	"DESCRICAO"	TEXT NOT NULL,
	"ID_PESSOA"	INTEGER,
	PRIMARY KEY("ID_REALIZACOES"),
	FOREIGN KEY("ID_PESSOA") REFERENCES "Pessoa"("ID_PESSOA")
);
CREATE TABLE IF NOT EXISTS "Habilidades" (
	"ID_HABILIDADE"	INTEGER NOT NULL,
	"TIPO"	TEXT NOT NULL,
	"NIVEL"	TEXT NOT NULL,
	"ID_PESSOA"	INTEGER,
	PRIMARY KEY("ID_HABILIDADE"),
	FOREIGN KEY("ID_PESSOA") REFERENCES "Pessoa"("ID_PESSOA")
);
CREATE TABLE IF NOT EXISTS "Personalidade" (
	"ID_PERSONALIDADE"	INTEGER NOT NULL,
	"TIPO"	TEXT NOT NULL,
	"NIVEL"	TEXT NOT NULL,
	"ID_PESSOA"	INTEGER,
	PRIMARY KEY("ID_PERSONALIDADE"),
	FOREIGN KEY("ID_PESSOA") REFERENCES "Pessoa"("ID_PESSOA")
);
COMMIT;
